require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - "bin/**/*"
    - "node_modules/**/*"

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Rails:
  Enabled: true

Rails/NotNullColumn:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    'default': '()'
    '%i': '()'
    '%w': '()'
